FACEBOOK_APP_ID: ""
FACEBOOK_SECRET: ""
MAILCHIMP_API_KEY: ""
MAILCHIMP_LIST_ID: ""
FOG_PROVIDER: AWS
FOG_DIRECTORY: ""
FOG_REGION: eu-west-1
AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:
GOOGLE_ACCOUNT_ID: ""
GMAIL_USERNAME: ""
GMAIL_PASSWORD: ""

TWITTER_CONSUMER_KEY: ""
TWITTER_CONSUMER_SECRET: ""
TWITTER_OAUTH_TOKEN: ""
TWITTER_OAUTH_TOKEN_SECRET: ""
TWITTER_API_KEY: ""
TWITTER_API_SECRET: ""

TYPEKIT_API_KEY: ""
MAILER_HOST: ""

AIRBRAKE_API_KEY: ""

development:
  SECRET_KEY_BASE: ""

  FACEBOOK_APP_ID: ""
  FACEBOOK_SECRET: ""

test:
  SECRET_KEY_BASE: ""

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  SECRET_KEY_BASE: ""

  FACEBOOK_APP_ID: ""
  FACEBOOK_SECRET: ""

  MAILCHIMP_LIST_ID: ""
  MAILER_HOST: ""

